version: '3.8'

services:
  python-genai:
    build: .
    container_name: python-genai
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - HOST=0.0.0.0
      - PORT=8000
      - PERSIST=true
      - GEMINI_MODEL=${GEMINI_MODEL:-gemini-2.5-flash-image-preview}
      - GEMINI_VIDEO_MODEL=${GEMINI_VIDEO_MODEL:-veo-3.1-generate-preview}
    volumes:
      # Mount volumes for persistent data
      - ./assets:/app/assets
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

